### ISSUE TITLE
Enforce HTTPS?

### ISSUE THREAD

**Issue by dar5hak** [elementary/appcenter-web#51] opened 2020-10-15 12:03 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Since this is hosted on GitHub Pages, can we redirect everyone to HTTPS by default? It's this option in the repo settings:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/8205055/96120283-e79fd280-0f0b-11eb-975d-289a388d4af1.png">

### To Reproduce
Open http://appcenter.elementary.io/

### Expected behavior
It should redirect to https://appcenter.elementary.io/

**Comment by cassidyjames** [comment] 2020-10-15 15:37
Yeah that's fine, except I'm currently seeing this in the settings. 

![Screenshot_20201015-093444~2](https://user-images.githubusercontent.com/611168/96152734-185f1800-0eca-11eb-9b68-8779521bca3c.png)


It might just require turning Pages off and back on, but that could result in a slight outage. @btkostner ideas?

**Comment by btkostner** [comment] 2020-10-15 17:05
https is being handled by cloudflare, that's probably the cause of the error. We can't enable strict https headers domain wide because we also host the deb repositories on the same domain (which can't be https). This will be fixed once we upgrade to flatpak repos and deprecate the deb repos. Then _everything_ can have the strict https headers.

**Comment by cassidyjames** [comment] 2020-10-15 17:48
@btkostner ah, is there a reason we're using Cloudflare for anything other than DNS here? Any assets are already being served from the AppStream domain over SSL, and this site is hosted on GitHub Pages (so no hosting fees for us). The blog is set up to be always HTTPS. :thinking: I might look at the difference between the Cloudflare and GitHub settings to investigate.

**Comment by cassidyjames** [comment] 2021-08-13 19:37
At some point we switched things around and forced HTTPS, so this can be closed.

**Closed by cassidyjames** 2021-08-13 19:37 UTC
